name: cat_ui
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  modal_bottom_sheet: ^2.0.0
  image_picker: ^0.8.4+10
  http: ^0.13.4
  url_launcher: ^6.0.20
  http_parser: ^4.0.0
  lottie: ^1.2.2
  flutter_staggered_grid_view: ^0.6.1
  cached_network_image: ^3.2.0
  custom_pop_up_menu: ^1.2.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro

